### ISSUE TITLE
CDB X Proposed Path Forward

### ISSUE THREAD

**Issue by MichalaH** [sofwerx/cdb2-concept#16]
All,
Thank you for your patience as the facilitator team and SOCOM took time to meet and better document our objectives.  Attached here is a slide deck that outlines our proposed path for this tech sprint.  It is a "proposed" path because while this is the best path forward in our perspective, we are open to suggestions and modifications.  

The list of "desired capabilities" is long, and overall this task is large.  We don't expect that all of these capabilities will be met, or that all the profiles will be built.  We would like to work on the pieces we can, as much as we can.  What work we are conducting now matches to which pieces of the proposed way forward?  What can we do in the short amount of time we have?  In the Engineering Report, we expect to be explicit about what was done, and what wasn't.

Please also consider how the different pieces of our proposed set of profiles work together or don't, what pieces overlap or don't, parts of the current CDB that remain unchanged, or that need changed, work we are doing now and where it fits, work that needs to be done and the order and dependencies, and terminology.  Let us know if this proposal adversely affects your ability to experiment.  We know some work will not be affected but some might.

As with all our GitHub discussions, points made here could end up in the ER as lessons learned, future topics for experimentation, design details, etc.

Note that all terminology used here is in flux and may be amended later.  We have to put terms on things in order to talk about them but we are open to suggestions.

Thank you all for your help!

[CDB-X_v4.pptx](https://github.com/sofwerx/cdb2-concept/files/5042629/CDB-X_v4.pptx)

NEW SCHEDULE:
•	Experimentation and Engineering Report Phases will now run concurrently until September 30
•	October will be focused on finishing the Engineering Report
•	The CDB SWG has offered to take on the task of writing the specification for the new version of CDB, which is yet to be named
•	Please contact Crystal at crystal.l.nedik.ctr@socom.mil with any questions about funding, business reports, or anything related to SOFWERX

**Comment by cnreediii** [comment]
I have been editing the Engineering Report (ER) based on some of the content provided in Michala's slides. The more recent changes are the Terms & Definitions section and the Models section (section 6). In section 6, I added a section on what the heck is foundation data and a proposal for what could be foundation data in CDB-X based on CDB 1.2. I also provided a draft definition for foundation data.

I have also added a use case sub-section based on the content of slide 6. In order to complete the ER, we actually need a few sentences describing each use case. I also reorganized the use cases (profiles?) a bit as some are actually stated as requirements, one is a general note, and one is probably long term future work. Obviously this is all drafty.

Finally, I took a look at the draft "conceptual model" this is actually a composite of conceptual, logical, and physical models. We will need to separate the different models and flush them out. We need to be careful to not specify implementation or platform specific content in the conceptual/logical model. This is necessary to meet the requirement/use case for an abstract configuration model.

**Comment by cnreediii** [comment]
Finally made it to the last slide. Lots of good content to chew on!

On the last slide, there is a statement about agreeing on one metadata standard and one attributes standard. From a conceptual and logical model perspective, this would be a mistake. Even in a core CDB-X standard, there is no reason to mandate a specific metadata and/or  attribute standard. In the current CDB standard, anyone of 7 (if I remember correctly) metadata standards may be specified. CDB 1.1 and after recommends a set of metadata elements that are supported in all of the 7 allowed metadata standards. In CDB X, we should mandate a minimal set of metadata elements and then also specify a set of recommended elements. This is what a number of existing OGC standards do. Also, a number of OGC interoperability initiatives have taken the same approach, although the list of elements is much longer/deeper than in the current CDB standard. If you want to make clear requirements in the core CDB-X standard, then mandate how time is expressed  and how character sets are expressed.

The same arguments can be made in relation to mandating only one attribute standard. "One ring does not rule them all" :-)

I also need to make a note regarding how there appears to be confusion/conflation of ideas related to structure and data. More on that later.

**Comment by MichalaH** [comment]
Here is an updated slide set that corrects what were slides 5 and 6, with listed desired capabilities and proposed profiles.  A few people contributed to this slide set so things got mixed up there and I apologize. 
[CDB-X_v5.pptx](https://github.com/sofwerx/cdb2-concept/files/5066477/CDB-X_v5.pptx)

**Comment by MichalaH** [comment]
"......my immediate reaction is that there are way too many profiles!!! "

There were a lot of things listed under the profiles slide that should not have been there.  I fixed and attached updated slide set as CDB-X_v5 above.

**Comment by MichalaH** [comment]
Project complete, closing admin items.
