### ISSUE TITLE
August Technical Update (report by 8-28)

### ISSUE THREAD

**Issue by MichalaH** [sofwerx/cdb2-concept#18]
Participant Name/Company:
Breakout Group:
Work Completed: list prototyping, development, TIEs, meetings, any and all work for this effort for the month
Work Planned: list work that is planned for the following month
Risks/Issues/Blockers: list any risks to accomplishing the work, anything that is blocking, or any issues

Paid participants, please use the above template to submit monthly technical work reports in a comment below.  I will give this info to SOCOM/SOFWERX as the monthly update.  Thank you!

**Comment by DavidFLOR** [comment]
David Graham/Eagle Cap Systems
Breakout Group(s):  High level metadata/integration; ER Editors
Attended all the meetings
Developed a Miro whiteboard to try to illustrate the overall concept of the work post-Sprint-week-Miro and after change of moderatores
Held multiple collaboration meetings/conversations with Mike Lokuta, Jay Freeman, and Carl Reed
Developed a first high-level collection of logical UML models for high-level CDB X metadata, concentrating on metadata to convey provenance/quality; temporal information for change management; and constraints for IP/licensing/security use; borrowing heavily from the NSG Metadata Foundation and the OGC Tilematrix set metadata conceptual model ER.
Developed a scenario/description for an integration analysis 'experiment' tracking metadata and CDB-X 'packaging' involved in a specific use-case for creating and disseminating a "small change" in a high detail; hi resolution LOD CDB dataset; wrote first draft asciidoc chapters for the attribution and top-level metadata ER section covering the week long virtual Sprint.

**Comment by cnreediii** [comment]
Carl Reed/Carl Reed &Associates
Breakout Group(s): Coverage Tiling/ ER Editor
**Work Completed:**
Attended all the meetings
Reviewed Miro whiteboard and took content to update the CDB-X Engineering report
Held multiple collaboration meetings/conversations with Coverage Tiling Subgroup, coordinated with David as Editor, collaborated with other groups via email and Git issues
Continued to add and update content in the Engineering report most recently in the 3D Modelling section.
**Work Planned**
Continue adding content to the ER and work with others to coordinate inclusion of new content. Next week will look at Coverage Tiling content inclusion.
**Risks**
Content not provided by other participants in a timely manner.

**Comment by ryanfranz** [comment]
Ryan Franz / FlightSafety International
Breakout Group:  Coverage Tiling
Attended all the meetings
Working on creating two different coverage types, 1) a low resolution world dataset, and 2) a high resolution inset.  I have the tiling implemented and producing imagery tiles, still working on the GeoPackage extension needed to store the data.
I plan on implementing elevation and raster material coverage types as well.

**Comment by PresagisHermann** [comment]
Hermann Brassard – Presagis
**Breakout Group** : 3D models
**Work completed:**
- Group meeting: 
o	Review focus of the group based on posted info on Miro board.
o	Review first results Anthony got with OpenFlight to glTF conversion
o	Discuss glTF extensions (review docx file  on the github branch https://github.com/sofwerx/cdb2-concept/tree/3Dmodels_prototype/3Dmodel_Prototype)
o	Discuss 3D model packaging. Initial dump of idea/questions are on Miro board block: Experimentation 1 - object model
- Produced a report on delta between glTF and OpenFlight  [link](https://github.com/sofwerx/cdb2-concept/blob/3Dmodels_prototype/3Dmodel_Prototype/CDB%20and%20OpenFlight_glTF_analysis.docx)
- Implemented a first OpenFlight to glTF converter for common constructs (no extensions)
- Produced first version of the glTF extension definition [link](o	https://github.com/sofwerx/cdb2-concept/blob/3Dmodels_prototype/3Dmodel_Prototype/CDB_ExtensionV2.xlsx)
- discussion on extension, both in a group mailing chain and on GITHUB [issue](https://github.com/sofwerx/cdb2-concept/issues/19)

**Work Planned:**
- Definition of glTF extension for CDB (json)
- Implementation of OpenFlight to glTF converter with extensions
- Definition of 3Dmodel indexing component
- Review of game engine 3D structures for interior (including indoor gml), navigation and collision to extract a common definition

**Risk/Issues/Blocker:**
- need more review form the other groups on the progress and direction
- need sync with tiling group as it impacts 3D models significantly.

**Comment by UnclePoole** [comment]
Gregory Peele - Geometric Progress LLC
**Breakout Group:** Attribution
**Work Completed:** 
- Created prototype C++ open source library implementing native code runtime for experimenting with CDB X proposed data dictionary schema from Miro board
- Initiated C++ implementation of proposed experimental CDB X SQLite data dictionary format per Miro board design
- Initiated C++ implementation of loader for GGDM 3.0 data dictionary Excel sheet to conduct mapping experiment
- Initiated C++ implementation of loader for CDB 1.0 data dictionary XML files to conduct mapping experiment
- Attended all but one meeting
- Ongoing Slack communication with Holly Black on data model mapping approaches
- Phone meeting with Andy Claar (NGA / FG3D) to discuss CDB attribution approach
- Delivered OWT data model documents to Andy Claar, Holly Black, and Randi Lisk
- (Funded by Army CCDC) Monthly data model collaboration with Army CCDC STTC contractors, presented CDB X status and plans to STTC team
- (Funded by Army CCDC) Monthly data model collaboration with Army PEOSTRI, VRICON, and Cesium on OWT, includes CDB X discussions
- (Funded by Army CCDC) Weekly data model collaboration with Unity, includes CDB X discussions
- (Funded by Army CCDC) Attended two out of three days of the OWT Technical Assessment for Capability Set 3, did not find any substantial changes in OWT direction or requirements that affect CDB X design and experiment plan

**Work Planned:**
- Complete C++ implementation of experimental CDB X SQLite data dictionary format and GGDM 3.0 and CDB 1.0 loaders
- Implement C++ code to automatically generate mappings from CDB 1.0 to GGDM 3.0 and store in CDB X format
- Cross-reference automated mappings with manually developed mappings and identify gaps
- Update Engineering Report to reflect findings of Attribution breakout group
- Update documentation to reflect goals of attribution experiment
- Cross-reference attribution findings with vector and 3D Model breakout groups
- Continue cross-contract and cross-agency meeting support regarding OWT and CDB X interoperability

**Risks/Issues/Blockers:**
- Substantial reduction in my work time availability in August due to faster-than-anticipated personal and Geometric Progress LLC move from Orlando, FL to Cocoa, FL, planning to make up lost time in September to work toward experiment completion

**Comment by freemanjay** [comment]
CAE 
Breakout Group: Vectors in Geopackage

Work Completed:
-- Supported various meetings and discussions 
-- Leveraged the CDB Productivity API to create a single GeoPackage that contains the global Joint Staff CDB vectors
-- Leveraged the CDB Productivity API to create a single GeoPackage that contains the global OSM vector data

Work Planned:
-- Experiment with performance of GeoPackages with very large volumes of data

Risk/Issues/Blocker:
-- None

**Comment by jerstlouis** [comment]
Jerome St-Louis - Ecere
**Breakout Group:** Tiling
**Work Completed in August:** 
- Attended regular and tiling group meetings
- Provided input in GitHub Tiling issues
- Implemented exporting JPG imagery tiles and GeoTIFF coverage tiles to GeoPackage
- Produced a first sample CDB X / GeoPackage ([Experiment 1](https://github.com/sofwerx/cdb2-concept/wiki/Tiling-GeoPackage-Experiment-1)), using the TileMatrixSet, Vector Tiles, Vector Tiles AttributesTable, Mapbox Vector Tiles and Gridded Coverage extensions, including imagery, elevation, geotypical and geospecific models (points only for now) and natural vector features
- Produced sample cdb.json metadata describing the content of the GeoPackage and where to find which layers
- Tested and fixed our OGC API map server to support directly accessing resources from this sample CDB X / GeoPackage using Features, Maps, Coverage and Tiles API
- Demonstrated 3D Tiles tileset generation visualized in Cesium from intermediate data store for CDB data (no textures yet)
- Tested and demonstrated visualization of prototype CDB X / GeoPackage in our visualization client (no models yet)

**Work Planned:**
- Produce a second test GeoPackage, this time for the larger San Diego dataset (work needed to be done to support heavier larger dataset)
- Implement support for splitting in multiple geopackages and producing the metadata describing where to find which layers and which LODs
- Implement support for exporting textures to glTF
- Prototype geospecific glTF model exports as single model containing all geospecific models in each tile (in the tiles table, more similar to integrated mesh / 3D Tiles / OWT approach)
- Prototype geospecific glTF model exports as a related table of 3D models being referenced by the vector tiles attributes table (more similar to CDB 1.x approach)
- Prototype geotypical glTF model exports as a related table of 3D model being referenced by the vector tiles attributes table
- Demonstrate 3D Tiles tileset generation visualized in Cesium directly from CDB X GeoPackage (with textures)
- Test and demonstrate visualization of prototype CDB X / GeoPackage in our visualization client including models

**Risks/Issues/Blockers:**
- Synchronization needed with Vector in geopackage and 3D Models groups

**Comment by holly-black** [comment]
Holly Black / CAE
Breakout Group: Attribution
Work Completed:
- Attended meetings
- Created UML process diagram for focused on NAS attribution schema
- Mapping previous CDB with TDS, GGDM, and NAS to discover missing attribution and features
- Met with NGA representatives to discuss aligning new CDB attribution schema within NGA
Work Planned:
- Complete mapping of attribution 
- Continue to work with NGA for feasibility of implementation
Risks/Issues/Blockers:
- Full understanding of the other work breakout groups conclusions and paths forward

**Comment by MichalaH** [comment]
Project complete, closing admin items.
