### ISSUE TITLE
September Technical Updates (due Sep 29)

### ISSUE THREAD

**Issue by MichalaH** [sofwerx/cdb2-concept#38]
Participant Name/Company:
Breakout Group:
Work Completed: list prototyping, development, TIEs, meetings, any and all work for this effort for the month
Work Planned: list work that is planned for the following month
Risks/Issues/Blockers: list any risks to accomplishing the work, anything that is blocking, or any issues

Paid participants, please use the above template to submit monthly technical work reports in a comment below. I will give this info to SOCOM/SOFWERX as the monthly update. The people we are expecting to see give updates are listed below.  

Please send me a Slack or email (mhill@cognitics.net) verifying your meeting attendance this month so I can make sure my notes are correct.  If you had someone attend meetings on your behalf, please list that person's name and when they attended.
•	Hermann Brassard
•	Ryan Franz
•	Jay Freeman
•	David Graham
•	Greg Peele
•	Carl Reed
•	Jerome St-Louis
•	Sean Lilley
Thank you!

**Comment by cnreediii** [comment]
Participant Name/Company: Carl Reed (Carl Reed &Associates)

Breakout Group: Coverages/Tiles and ER Editor

Work Completed: list prototyping, development, TIEs, meetings, any and all work for this effort for the month:  Attended all group conference calls, collaborated with the Coverages/Tiles subgroup, participated in Slack and Git Issues discussions, and continued work on the draft CDB X ER. The latter included more work on some of the boilerplate content as well as the Attribute attribute section and creating a new annex C.

Work Planned: list work that is planned for the following month: Continue working away on the ER so that we are not in crisis mode at the end of October.

Risks/Issues/Blockers: list any risks to accomplishing the work, anything that is blocking, or any issues: The Sub-groups not getting me draft content to work with!

**Comment by PresagisHermann** [comment]
**Participant Name/Company:** Hermann Brassard – Presagis
**Breakout Group :** 3D models

**Work completed:**
CDB X meeting attendance: Attended 4 of 4 meetings this month (Herm 3 and Anthony Mirabeau 4)

Define most of the CDB required glTF extensions – produced the json schema for it – got review from Cesium.

Implemented OpenFlight to glTF converter C++ application and tested a few different models. See progress and models [here](https://github.com/sofwerx/cdb2-concept/tree/3Dmodels_prototype/3Dmodel_Prototype) 

Very active exchange with the tiling group over e-mail than migrated to GitHUB. We now have enough to progress the 3D model conversion to group into tile in a consistent way with the rest of the CDB X efforts. Yet.... much remains to be decided!

Defined a 3D model component index file structure to allow regrouping and indexing of all 3D model related data as opposed to storing them in different folder. 

Initial implementation of a script to convert a CDB 1.X GS model dataset from OpenFlight models into glTF, with textures and using the glTF CDB extensions. The prototype script is regrouping the various LODs of a model a folder with the index file.

**Work Planned:**

- Complete the script to convert CDB to proposed glTF models and tiling packaging
- Support ER

**Risk/Issues/Blocker:**

**Comment by jerstlouis** [comment]
Jerome St-Louis - Ecere
**Breakout Group:** Tiling
**Work Completed in September:** 
- Attended regular and tiling group meetings
- Provided input in GitHub Tiling issues
- Produced a second test GeoPackage, this time for the larger San Diego dataset (work needed to be done to support heavier larger dataset)
- Implemented support for splitting in multiple geopackages and producing the metadata describing where to find which layers and which LODs
- Implemented support for exporting textures to glTF
- Demonstrated 3D Tiles tileset generation visualized in Cesium from intermediate data store for CDB data (with textures)
- Tested and demonstrated visualization of prototype CDB X / GeoPackage in our visualization client (no models yet)
- Tested tiled GeoPackages produced by Flight Safety and provided feedback

**Work Planned:**
- Prototype geospecific glTF model exports as single model containing all geospecific models in each tile (in the tiles table, more similar to integrated mesh / 3D Tiles / OWT approach)
- Prototype geospecific glTF model exports as a related table of 3D models being referenced by the vector tiles attributes table (more similar to CDB 1.x approach)
- Prototype geotypical glTF model exports as a related table of 3D model being referenced by the vector tiles attributes table
- Test and demonstrate visualization of prototype CDB X / GeoPackage in our visualization client including models
- (Stretch goal) Demonstrate 3D Tiles tileset generation visualized in Cesium directly from CDB X GeoPackage (with textures)
- Contribute to engineering report

**Risks/Issues/Blockers:**
- None

**Comment by DavidFLOR** [comment]
David Graham - Eagle Cap Systems
High Level Integration / Metadata; ER Editor
Attended all the meetings except one, for which advance notice was given to the moderator
Completed WIP draft discussion document exploring legacy CDB versioning;
Following the experiments, Github issues discussions, and Slack discussions to continue to attempt to figure out what integration and metadata implications for which we have consensus from the Sprint;
The plan for October is pretty intensive involvement to support Carl as the ER Editor, and to form and express my own view of the integration and metadata decisions that have been achieved in the Sprint, and those that remain for a starting point of OGC CDB X
Inputs from the other breakout groups for the ER; inputs from the other breakout groups answering integration questions previously described in my Miro board.

**Comment by ryanfranz** [comment]
**Participant Name/Company:**  Ryan Franz, FlightSafety International

**Breakout Group:**  Tiling/Coverages
Attended all four meetings this month

**Work Completed:**
*  Created four experimental CDB X tiling examples:
   * Low resolution imagery for the whole world
   * Low resolution imagery with a high resolution inset
   * Low resolution imagery and elevation in different sets of GeoPackages
   * Low resolution imagery and elevation combined into the same set of GeoPackages
* Documenting possible issues with the test datasets that we have created on the wiki page
   * https://github.com/sofwerx/cdb2-concept/wiki/FlightSafety-GeoPackage-Tiling-Experiments
* Experimenting with converting CDB to 3D Tiles for visualization purposes
* Participated in the discussion with the 3D models group

**Work Planned:**
* Work on the engineering report
* Investigate the work done by the 3D models group
* If time allows, test the performance of the GeoPackage with all the road data of the US

**Risks/Issues/Blockers:** No risks right now

**Comment by UnclePoole** [comment]
Participant Name/Company: Greg Peele (Geometric Progress LLC)

Breakout Group: Attribution

**Work Completed:**
- Continued metamodel mapping of CDB 1.1 to proposed CDB X design to identify gaps in metamodel, filed tickets on all findings or ideas
- Determined that CDB has two orthogonal concepts of entity abstraction that need to be captured: category/subcategory (used for model organization) and dataset (used for data containerization and attribution)
- CDB 1.1 binds attributes at the dataset level rather than the entity level, so generalizations such as datasets need to be able to reference attributes for the mapping to work
- Adjusted metamodel so that all "things" including category/subcategory and dataset are Entity definitions, with different roles such as Generalization, Representation, Aggregation, Composition, etc. (removed separate definitions for Geometry, Linkage, Theme)
- Continued work on code experiment to load CDB 1.1 XML feature/attribute dictionary to identify gaps in metadata and map to GGDM 3.0, will transition effort to Army CCDC funding to convert experiment into usable library for OWT
- Conducted deep assessment of building interior entities and attribution against existing standards NAS/GGDM, IFC 4.1 and IFC 4.3 experimental, CDB 1.1, CityGML and IndoorGML, and preliminary assessment of Apple IMDF and NATO JC3IEDM/MIM, determined that all existing standards diverged substantially with each other on building component types and organization
- Attended all CDB X Tech Sprint meetings
- Substantial ongoing discussion in Slack regarding OGC and building interior attribution

**Work Planned:**
- Capture attribution findings and recommendations in Engineering Report
- Create recommended strategy for enhancing building interior data model in CDB
- Cross-reference attribution findings with GeoPackage experiments

**Comment by lilleyse** [comment]
**Participant Name/Company:** Sean Lilley – Cesium
**Breakout Group:** 3D models

**Work completed:**

- Provided feedback on CDB glTF extension
- Identified ares of convergence for CDB X and 3D Tiles Next - glTF, implicit tiling schemes, raster imagery and terrain support - with the goal of improving CDB and OWT Well-Formed Format compatibility.
- Discussed CDB X work with OWT stakeholders to find common ground for a glTF simulation extension with a focus on switch nodes and articulations.
- Participated in the OGC Interopable Gaming and Simulation Sprint and prototyped a CDB to 3D Tiles converter

**Work Planned:**

- Document CDB glTF extension for engineering report

**Risk/Issues/Blocker:**

- None

**Comment by freemanjay** [comment]
Participant Name/Company: CAE
Breakout Group: Vectors

Work completed:
comparison completed for feature code mapping TDS 7.0 / TDS 6.0/ GGDM/ CDB

Work Planned:
Draft report.

**Comment by MichalaH** [comment]
Project complete, closing admin items.
